import { AbilityRegistry } from '../ability-registry';
import { SPECS as abaddonAphoticShield } from './abaddon_aphotic_shield';
import { SPECS as abaddonBorrowedTime } from './abaddon_borrowed_time';
import { SPECS as abaddonDeathCoil } from './abaddon_death_coil';
import { SPECS as ancientApparitionChillingTouch } from './ancient_apparition_chilling_touch';
import { SPECS as axeBattleHunger } from './axe_battle_hunger';
import { SPECS as axeBerserkersCall } from './axe_berserkers_call';
import { SPECS as axeCullingBlade } from './axe_culling_blade';
import { SPECS as baneFiendsGrip } from './bane_fiends_grip';
import { SPECS as baneNightmare } from './bane_nightmare';
import { SPECS as bloodseekerBloodrage } from './bloodseeker_bloodrage';
import { SPECS as bloodseekerRupture } from './bloodseeker_rupture';
import { SPECS as bountyHunterJinada } from './bounty_hunter_jinada';
import { SPECS as bountyHunterTrack } from './bounty_hunter_track';
import { SPECS as bountyHunterWindWalk } from './bounty_hunter_wind_walk';
import { SPECS as bristlebackQuillSpray } from './bristleback_quill_spray';
import { SPECS as chibiHit } from './chibi_hit';
import { SPECS as chibiMonster } from './chibi_monster';
import { SPECS as crystalMaidenFreezingField } from './crystal_maiden_freezing_field';
import { SPECS as dazzleShadowWave } from './dazzle_shadow_wave';
import { SPECS as dazzleShallowGrave } from './dazzle_shallow_grave';
import { SPECS as deathProphetExorcism } from './death_prophet_exorcism';
import { SPECS as deathProphetSpiritSiphon } from './death_prophet_spirit_siphon';
import { SPECS as doomBringerInfernalBlade } from './doom_bringer_infernal_blade';
import { SPECS as dragonKnightBreatheFire } from './dragon_knight_breathe_fire';
import { SPECS as dragonKnightDragonTail } from './dragon_knight_dragon_tail';
import { SPECS as dragonKnightElderDragonForm } from './dragon_knight_elder_dragon_form';
import { SPECS as dragonKnightFireball } from './dragon_knight_fireball';
import { SPECS as drowRangerFrostArrows } from './drow_ranger_frost_arrows';
import { SPECS as drowRangerGlacier } from './drow_ranger_glacier';
import { SPECS as drowRangerMultishot } from './drow_ranger_multishot';
import { SPECS as drowRangerWaveOfSilence } from './drow_ranger_wave_of_silence';

export function registerAbilitySpecsAToD(): void {
  AbilityRegistry.registerAll(abaddonAphoticShield);
  AbilityRegistry.registerAll(abaddonBorrowedTime);
  AbilityRegistry.registerAll(abaddonDeathCoil);
  AbilityRegistry.registerAll(ancientApparitionChillingTouch);
  AbilityRegistry.registerAll(axeBattleHunger);
  AbilityRegistry.registerAll(axeBerserkersCall);
  AbilityRegistry.registerAll(axeCullingBlade);
  AbilityRegistry.registerAll(baneFiendsGrip);
  AbilityRegistry.registerAll(baneNightmare);
  AbilityRegistry.registerAll(bloodseekerBloodrage);
  AbilityRegistry.registerAll(bloodseekerRupture);
  AbilityRegistry.registerAll(bountyHunterJinada);
  AbilityRegistry.registerAll(bountyHunterTrack);
  AbilityRegistry.registerAll(bountyHunterWindWalk);
  AbilityRegistry.registerAll(bristlebackQuillSpray);
  AbilityRegistry.registerAll(chibiHit);
  AbilityRegistry.registerAll(chibiMonster);
  AbilityRegistry.registerAll(crystalMaidenFreezingField);
  AbilityRegistry.registerAll(dazzleShadowWave);
  AbilityRegistry.registerAll(dazzleShallowGrave);
  AbilityRegistry.registerAll(deathProphetExorcism);
  AbilityRegistry.registerAll(deathProphetSpiritSiphon);
  AbilityRegistry.registerAll(doomBringerInfernalBlade);
  AbilityRegistry.registerAll(dragonKnightBreatheFire);
  AbilityRegistry.registerAll(dragonKnightDragonTail);
  AbilityRegistry.registerAll(dragonKnightElderDragonForm);
  AbilityRegistry.registerAll(dragonKnightFireball);
  AbilityRegistry.registerAll(drowRangerFrostArrows);
  AbilityRegistry.registerAll(drowRangerGlacier);
  AbilityRegistry.registerAll(drowRangerMultishot);
  AbilityRegistry.registerAll(drowRangerWaveOfSilence);
}
