import { AbilityRegistry } from '../ability-registry';
import { SPECS as medusaGorgonGrasp } from './medusa_gorgon_grasp';
import { SPECS as medusaMysticSnake } from './medusa_mystic_snake';
import { SPECS as medusaSplitShot } from './medusa_split_shot';
import { SPECS as medusaStoneGaze } from './medusa_stone_gaze';
import { SPECS as mikuDance } from './miku_dance';
import { SPECS as mikuHadouken } from './miku_hadouken';
import { SPECS as necrolyteDeathPulse } from './necrolyte_death_pulse';
import { SPECS as necrolyteDeathSeeker } from './necrolyte_death_seeker';
import { SPECS as necrolyteGhostShroud } from './necrolyte_ghost_shroud';
import { SPECS as necrolyteReapersScythe } from './necrolyte_reapers_scythe';
import { SPECS as nevermoreFrenzy } from './nevermore_frenzy';
import { SPECS as nevermoreRequiem } from './nevermore_requiem';
import { SPECS as nevermoreShadowraze1 } from './nevermore_shadowraze1';
import { SPECS as nevermoreShadowraze2 } from './nevermore_shadowraze2';
import { SPECS as nevermoreShadowraze3 } from './nevermore_shadowraze3';
import { SPECS as ogreMagiBloodlust } from './ogre_magi_bloodlust';
import { SPECS as ogreMagiFireblast } from './ogre_magi_fireblast';
import { SPECS as ogreMagiIgnite } from './ogre_magi_ignite';
import { SPECS as ogreMagiSmash } from './ogre_magi_smash';
import { SPECS as ogreMagiUnrefinedFireblast } from './ogre_magi_unrefined_fireblast';
import { SPECS as omniknightAngelicFlight } from './omniknight_angelic_flight';
import { SPECS as omniknightGuardianAngel } from './omniknight_guardian_angel';
import { SPECS as omniknightHammerOfPurity } from './omniknight_hammer_of_purity';
import { SPECS as omniknightMartyr } from './omniknight_martyr';
import { SPECS as omniknightPurification } from './omniknight_purification';
import { SPECS as oracleFalsePromise } from './oracle_false_promise';
import { SPECS as oracleFatesEdict } from './oracle_fates_edict';
import { SPECS as oracleFortunesEnd } from './oracle_fortunes_end';
import { SPECS as oraclePurifyingFlames } from './oracle_purifying_flames';
import { SPECS as phantomAssassinBlur } from './phantom_assassin_blur';
import { SPECS as phantomAssassinFanOfKnives } from './phantom_assassin_fan_of_knives';
import { SPECS as phantomAssassinPhantomStrike } from './phantom_assassin_phantom_strike';
import { SPECS as pudgeDismember } from './pudge_dismember';
import { SPECS as pudgeFleshHeap } from './pudge_flesh_heap';
import { SPECS as pudgeRot } from './pudge_rot';
import { SPECS as rikiBlinkStrike } from './riki_blink_strike';
import { SPECS as rikiSmokeScreen } from './riki_smoke_screen';
import { SPECS as rikiTricksOfTheTrade } from './riki_tricks_of_the_trade';

export function registerAbilitySpecsMToR(): void {
  AbilityRegistry.registerAll(medusaGorgonGrasp);
  AbilityRegistry.registerAll(medusaMysticSnake);
  AbilityRegistry.registerAll(medusaSplitShot);
  AbilityRegistry.registerAll(medusaStoneGaze);
  AbilityRegistry.registerAll(mikuDance);
  AbilityRegistry.registerAll(mikuHadouken);
  AbilityRegistry.registerAll(necrolyteDeathPulse);
  AbilityRegistry.registerAll(necrolyteDeathSeeker);
  AbilityRegistry.registerAll(necrolyteGhostShroud);
  AbilityRegistry.registerAll(necrolyteReapersScythe);
  AbilityRegistry.registerAll(nevermoreFrenzy);
  AbilityRegistry.registerAll(nevermoreRequiem);
  AbilityRegistry.registerAll(nevermoreShadowraze1);
  AbilityRegistry.registerAll(nevermoreShadowraze2);
  AbilityRegistry.registerAll(nevermoreShadowraze3);
  AbilityRegistry.registerAll(ogreMagiBloodlust);
  AbilityRegistry.registerAll(ogreMagiFireblast);
  AbilityRegistry.registerAll(ogreMagiIgnite);
  AbilityRegistry.registerAll(ogreMagiSmash);
  AbilityRegistry.registerAll(ogreMagiUnrefinedFireblast);
  AbilityRegistry.registerAll(omniknightAngelicFlight);
  AbilityRegistry.registerAll(omniknightGuardianAngel);
  AbilityRegistry.registerAll(omniknightHammerOfPurity);
  AbilityRegistry.registerAll(omniknightMartyr);
  AbilityRegistry.registerAll(omniknightPurification);
  AbilityRegistry.registerAll(oracleFalsePromise);
  AbilityRegistry.registerAll(oracleFatesEdict);
  AbilityRegistry.registerAll(oracleFortunesEnd);
  AbilityRegistry.registerAll(oraclePurifyingFlames);
  AbilityRegistry.registerAll(phantomAssassinBlur);
  AbilityRegistry.registerAll(phantomAssassinFanOfKnives);
  AbilityRegistry.registerAll(phantomAssassinPhantomStrike);
  AbilityRegistry.registerAll(pudgeDismember);
  AbilityRegistry.registerAll(pudgeFleshHeap);
  AbilityRegistry.registerAll(pudgeRot);
  AbilityRegistry.registerAll(rikiBlinkStrike);
  AbilityRegistry.registerAll(rikiSmokeScreen);
  AbilityRegistry.registerAll(rikiTricksOfTheTrade);
}
