import { AbilityRegistry } from '../ability-registry';
import { SPECS as earthshakerEchoSlam } from './earthshaker_echo_slam';
import { SPECS as earthshakerEnchantTotem } from './earthshaker_enchant_totem';
import { SPECS as enchantressImpetus } from './enchantress_impetus';
import { SPECS as getDown } from './get_down';
import { SPECS as imbaChaosKnightPhantasm } from './imba_chaos_knight_phantasm';
import { SPECS as jakiroDualBreath } from './jakiro_dual_breath';
import { SPECS as jakiroLiquidFire } from './jakiro_liquid_fire';
import { SPECS as jakiroMacropyre } from './jakiro_macropyre';
import { SPECS as juggernautBladeFury } from './juggernaut_blade_fury';
import { SPECS as juggernautHealingWard } from './juggernaut_healing_ward';
import { SPECS as juggernautOmniSlash } from './juggernaut_omni_slash';
import { SPECS as juggernautSwiftSlash } from './juggernaut_swift_slash';
import { SPECS as kunkkaGhostship } from './kunkka_ghostship';
import { SPECS as kunkkaTidalWave } from './kunkka_tidal_wave';
import { SPECS as kunkkaTidebringer } from './kunkka_tidebringer';
import { SPECS as kunkkaTorrent } from './kunkka_torrent';
import { SPECS as kunkkaXMarksTheSpot } from './kunkka_x_marks_the_spot';
import { SPECS as lichChainFrost } from './lich_chain_frost';
import { SPECS as lichFrostArmor } from './lich_frost_armor';
import { SPECS as lichFrostNova } from './lich_frost_nova';
import { SPECS as lichFrostShield } from './lich_frost_shield';
import { SPECS as lichIceSpire } from './lich_ice_spire';
import { SPECS as lichSinisterGaze } from './lich_sinister_gaze';
import { SPECS as linaFlameCloak } from './lina_flame_cloak';
import { SPECS as linaLagunaBlade } from './lina_laguna_blade';
import { SPECS as lionFingerOfDeath } from './lion_finger_of_death';
import { SPECS as lionImpale } from './lion_impale';
import { SPECS as lionManaDrain } from './lion_mana_drain';
import { SPECS as lionVoodoo } from './lion_voodoo';
import { SPECS as liuKick } from './liu_kick';
import { SPECS as lunaEclipse } from './luna_eclipse';
import { SPECS as lunaLunarOrbit } from './luna_lunar_orbit';

export function registerAbilitySpecsEToL(): void {
  AbilityRegistry.registerAll(earthshakerEchoSlam);
  AbilityRegistry.registerAll(earthshakerEnchantTotem);
  AbilityRegistry.registerAll(enchantressImpetus);
  AbilityRegistry.registerAll(getDown);
  AbilityRegistry.registerAll(imbaChaosKnightPhantasm);
  AbilityRegistry.registerAll(jakiroDualBreath);
  AbilityRegistry.registerAll(jakiroLiquidFire);
  AbilityRegistry.registerAll(jakiroMacropyre);
  AbilityRegistry.registerAll(juggernautBladeFury);
  AbilityRegistry.registerAll(juggernautHealingWard);
  AbilityRegistry.registerAll(juggernautOmniSlash);
  AbilityRegistry.registerAll(juggernautSwiftSlash);
  AbilityRegistry.registerAll(kunkkaGhostship);
  AbilityRegistry.registerAll(kunkkaTidalWave);
  AbilityRegistry.registerAll(kunkkaTidebringer);
  AbilityRegistry.registerAll(kunkkaTorrent);
  AbilityRegistry.registerAll(kunkkaXMarksTheSpot);
  AbilityRegistry.registerAll(lichChainFrost);
  AbilityRegistry.registerAll(lichFrostArmor);
  AbilityRegistry.registerAll(lichFrostNova);
  AbilityRegistry.registerAll(lichFrostShield);
  AbilityRegistry.registerAll(lichIceSpire);
  AbilityRegistry.registerAll(lichSinisterGaze);
  AbilityRegistry.registerAll(linaFlameCloak);
  AbilityRegistry.registerAll(linaLagunaBlade);
  AbilityRegistry.registerAll(lionFingerOfDeath);
  AbilityRegistry.registerAll(lionImpale);
  AbilityRegistry.registerAll(lionManaDrain);
  AbilityRegistry.registerAll(lionVoodoo);
  AbilityRegistry.registerAll(liuKick);
  AbilityRegistry.registerAll(lunaEclipse);
  AbilityRegistry.registerAll(lunaLunarOrbit);
}
