import { AbilityRegistry } from '../ability-registry';
import { SPECS as sandkingBurrowstrike } from './sandking_burrowstrike';
import { SPECS as sandkingEpicenter } from './sandking_epicenter';
import { SPECS as sandkingSandStorm } from './sandking_sand_storm';
import { SPECS as sandkingScorpionStrike } from './sandking_scorpion_strike';
import { SPECS as shadowShamanEtherShock } from './shadow_shaman_ether_shock';
import { SPECS as shadowShamanMassSerpentWard } from './shadow_shaman_mass_serpent_ward';
import { SPECS as shadowShamanShackles } from './shadow_shaman_shackles';
import { SPECS as shadowShamanUrnaconda } from './shadow_shaman_urnaconda';
import { SPECS as shadowShamanVoodoo } from './shadow_shaman_voodoo';
import { SPECS as silencerGlaivesOfWisdom } from './silencer_glaives_of_wisdom';
import { SPECS as skeletonKingHellfireBlast } from './skeleton_king_hellfire_blast';
import { SPECS as skywrathMageConcussiveShot } from './skywrath_mage_concussive_shot';
import { SPECS as skywrathMageMysticFlare } from './skywrath_mage_mystic_flare';
import { SPECS as slarkSaltwaterShiv } from './slark_saltwater_shiv';
import { SPECS as sniperAssassinate } from './sniper_assassinate';
import { SPECS as sniperShrapnel } from './sniper_shrapnel';
import { SPECS as sniperTakeAim } from './sniper_take_aim';
import { SPECS as spectreHaunt } from './spectre_haunt';
import { SPECS as spectreSpectralDagger } from './spectre_spectral_dagger';
import { SPECS as svenGodsStrength } from './sven_gods_strength';
import { SPECS as svenWarcry } from './sven_warcry';
import { SPECS as tinkerDeployTurrets } from './tinker_deploy_turrets';
import { SPECS as tinkerLaser } from './tinker_laser';
import { SPECS as tinkerMarchOfTheMachines } from './tinker_march_of_the_machines';
import { SPECS as tinkerRearmLua } from './tinker_rearm_lua';
import { SPECS as tinkerWarpGrenade } from './tinker_warp_grenade';
import { SPECS as tinyToss } from './tiny_toss';
import { SPECS as tinyTreeGrab } from './tiny_tree_grab';
import { SPECS as tuskWalrusPunch } from './tusk_walrus_punch';
import { SPECS as vengefulspiritNetherSwap } from './vengefulspirit_nether_swap';
import { SPECS as viperNethertoxin } from './viper_nethertoxin';
import { SPECS as viperNoseDive } from './viper_nose_dive';
import { SPECS as viperPoisonAttack } from './viper_poison_attack';
import { SPECS as viperViperStrike } from './viper_viper_strike';
import { SPECS as warlockRainOfChaos } from './warlock_rain_of_chaos';
import { SPECS as warlockUpheaval } from './warlock_upheaval';
import { SPECS as windrunnerFocusfire } from './windrunner_focusfire';
import { SPECS as windrunnerPowershot } from './windrunner_powershot';
import { SPECS as windrunnerWhirlwindCustom } from './windrunner_whirlwind_custom';
import { SPECS as windrunnerWindrun } from './windrunner_windrun';
import { SPECS as winterWyvernArcticBurn } from './winter_wyvern_arctic_burn';
import { SPECS as witchDoctorDeathWard } from './witch_doctor_death_ward';
import { SPECS as witchDoctorVoodooRestoration } from './witch_doctor_voodoo_restoration';
import { SPECS as witchDoctorVoodooSwitcheroo } from './witch_doctor_voodoo_switcheroo';
import { SPECS as zuusArcLightning } from './zuus_arc_lightning';
import { SPECS as zuusCloud } from './zuus_cloud';
import { SPECS as zuusHeavenlyJump } from './zuus_heavenly_jump';
import { SPECS as zuusLightningBolt } from './zuus_lightning_bolt';
import { SPECS as zuusThundergodsWrath } from './zuus_thundergods_wrath';

export function registerAbilitySpecsSToZ(): void {
  AbilityRegistry.registerAll(sandkingBurrowstrike);
  AbilityRegistry.registerAll(sandkingEpicenter);
  AbilityRegistry.registerAll(sandkingSandStorm);
  AbilityRegistry.registerAll(sandkingScorpionStrike);
  AbilityRegistry.registerAll(shadowShamanEtherShock);
  AbilityRegistry.registerAll(shadowShamanMassSerpentWard);
  AbilityRegistry.registerAll(shadowShamanShackles);
  AbilityRegistry.registerAll(shadowShamanUrnaconda);
  AbilityRegistry.registerAll(shadowShamanVoodoo);
  AbilityRegistry.registerAll(silencerGlaivesOfWisdom);
  AbilityRegistry.registerAll(skeletonKingHellfireBlast);
  AbilityRegistry.registerAll(skywrathMageConcussiveShot);
  AbilityRegistry.registerAll(skywrathMageMysticFlare);
  AbilityRegistry.registerAll(slarkSaltwaterShiv);
  AbilityRegistry.registerAll(sniperAssassinate);
  AbilityRegistry.registerAll(sniperShrapnel);
  AbilityRegistry.registerAll(sniperTakeAim);
  AbilityRegistry.registerAll(spectreHaunt);
  AbilityRegistry.registerAll(spectreSpectralDagger);
  AbilityRegistry.registerAll(svenGodsStrength);
  AbilityRegistry.registerAll(svenWarcry);
  AbilityRegistry.registerAll(tinkerDeployTurrets);
  AbilityRegistry.registerAll(tinkerLaser);
  AbilityRegistry.registerAll(tinkerMarchOfTheMachines);
  AbilityRegistry.registerAll(tinkerRearmLua);
  AbilityRegistry.registerAll(tinkerWarpGrenade);
  AbilityRegistry.registerAll(tinyToss);
  AbilityRegistry.registerAll(tinyTreeGrab);
  AbilityRegistry.registerAll(tuskWalrusPunch);
  AbilityRegistry.registerAll(vengefulspiritNetherSwap);
  AbilityRegistry.registerAll(viperNethertoxin);
  AbilityRegistry.registerAll(viperNoseDive);
  AbilityRegistry.registerAll(viperPoisonAttack);
  AbilityRegistry.registerAll(viperViperStrike);
  AbilityRegistry.registerAll(warlockRainOfChaos);
  AbilityRegistry.registerAll(warlockUpheaval);
  AbilityRegistry.registerAll(windrunnerFocusfire);
  AbilityRegistry.registerAll(windrunnerPowershot);
  AbilityRegistry.registerAll(windrunnerWhirlwindCustom);
  AbilityRegistry.registerAll(windrunnerWindrun);
  AbilityRegistry.registerAll(winterWyvernArcticBurn);
  AbilityRegistry.registerAll(witchDoctorDeathWard);
  AbilityRegistry.registerAll(witchDoctorVoodooRestoration);
  AbilityRegistry.registerAll(witchDoctorVoodooSwitcheroo);
  AbilityRegistry.registerAll(zuusArcLightning);
  AbilityRegistry.registerAll(zuusCloud);
  AbilityRegistry.registerAll(zuusHeavenlyJump);
  AbilityRegistry.registerAll(zuusLightningBolt);
  AbilityRegistry.registerAll(zuusThundergodsWrath);
}
