name: Automerge Release PR
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto_merge:
    if: |
      github.base_ref == 'main'
      && github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Enable Pull Request Squash Automerge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: merge
