name: Create Pull Request to develop
on:
  workflow_dispatch:

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name
        id: get_branch
        run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"

      - name: Get commit log
        id: get_log
        run: echo "::set-output name=log::$(git log --pretty=format:'- %s' origin/develop..HEAD)"

      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: develop

      - name: Reset promotion branch
        run: |
          git fetch origin ${{ steps.get_branch.outputs.branch }}:${{ steps.get_branch.outputs.branch }}
          git reset --hard ${{ steps.get_branch.outputs.branch }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          title: Update from ${{ steps.get_branch.outputs.branch }}
          body: |
            Changes in this pull request:
            ${{ steps.get_log.outputs.log }}
          branch: ${{ steps.get_branch.outputs.branch }}
          base: develop
