name: Create Pull Request to develop
on:
  workflow_dispatch:

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Set color
        id: color-selector
        run: echo "SELECTED_COLOR=green" >> "$GITHUB_OUTPUT"
      - name: Get color
        env:
          SELECTED_COLOR: ${{ steps.color-selector.outputs.SELECTED_COLOR }}
        run: echo "The selected color is $SELECTED_COLOR"

      - name: Get branch name
        id: get_branch
        run: echo "name=branch::${GITHUB_REF#refs/heads/}" >> "$GITHUB_OUTPUT"

      - name: show branch name
        run: echo ${{ steps.get_branch.outputs.branch }}

      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: develop

      - name: Reset promotion branch
        run: |
          git fetch origin ${{ steps.get_branch.outputs.branch }}:${{ steps.get_branch.outputs.branch }}
          git reset --hard ${{ steps.get_branch.outputs.branch }}

      - name: Get commit log
        id: get_log
        run: |
          echo "name=log::$(git log --pretty=format:'- %s' origin/develop..HEAD)" >> "$GITHUB_OUTPUT"
          echo "name=log::$(git log --pretty=format:'- %s' origin/develop..HEAD)"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          title: Update from ${{ steps.get_branch.outputs.branch }}
          body: |
            Changes in this pull request:
            ${{ steps.get_log.outputs.log }}
          branch: ${{ steps.get_branch.outputs.branch }}
          base: develop
