name: Create Pull Request to develop
on:
  workflow_dispatch:

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Get branch name
        id: get_branch
        run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"

      - name: Use branch name
        run: echo "Current branch is ${{ steps.get_branch.outputs.branch }}"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Update from ${{ steps.get_branch.outputs.branch }}
          branch: ${{ steps.get_branch.outputs.branch }}-develop
          base: develop
